[tool.poetry]
name = "ss13-tools"
version = "0.0.1"
description = "Tools for Space Station 13."

license = "MIT"
authors = ["Mislav Jaksic <jaksicmislav@gmail.com>"]
maintainers = []
readme = "README.md"

homepage = "https://github.com/MislavJaksic/Space-Station-13-Tools"
repository = "https://github.com/MislavJaksic/Space-Station-13-Tools"
documentation = "https://github.com/MislavJaksic/Space-Station-13-Tools"

keywords = []

classifiers = []

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.22.0"

[tool.poetry.dev-dependencies]
pytest-cov = "^2.8.1"
black = "^19.10b0"
pytest = "^5.2"
sphinx = "^2.3.1"

[tool.poetry.scripts]
ss13-tools = "ss13_tools.runner:run"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
